/**
 * GENERATED by tools/facts-claims.ts — DO NOT EDIT.
 *
 * Claims data for the descent page, extracted verbatim (machine-checked)
 * from the private FACTS.md ledger at grade. C-section (prohibited)
 * claims are excluded by construction; UNGRADED entries render dimmer
 * than DEFENSIBLE, never heavier.
 *
 * source: FACTS.md sha256 e5ad4dd537c29d26f0b0f624f54a23535a69e7ba7add4dfbe2944e871ff96d22
 */

import type { RenderedClaim } from "../../../tools/facts-claims.ts";

export const RENDERED_CLAIMS: readonly RenderedClaim[] = [
  {
    "chipLabel": "receipt: Humana Studio H press · Fierce Healthcare",
    "edge": "right",
    "id": "S1",
    "sceneId": "corridor",
    "slot": "S1",
    "text": "Enterprise LLM products inside a Fortune-50 payer, 2022–24.",
    "grade": "DEFENSIBLE",
    "gradeNote": "DEFENSIBLE (employer work internal; forks/dates public)."
  },
  {
    "chipHref": "https://collegearts.yale.edu/events/shows-screenings/reverie",
    "chipLabel": "receipt: collegearts.yale.edu (Reverie, Apr 2017)",
    "edge": "left",
    "id": "R9",
    "sceneId": "stage",
    "slot": "R9-president",
    "text": "President (2017) of a ~$200k/yr 501(c)(3) theater",
    "grade": "UNGRADED",
    "gradeNote": "(ungraded in source; receipts are public and re-runnable: yale.edu, Yale Daily News, IRS 990s.)"
  },
  {
    "caveat": "ungraded in source; receipts are public and re-runnable: yale.edu, Yale Daily News, IRS 990s",
    "edge": "left",
    "id": "R9",
    "sceneId": "stage",
    "slot": "R9-credits",
    "text": "Yale College Arts biography page (yale.edu) lists 9 production credits 2016–19",
    "grade": "UNGRADED",
    "gradeNote": "(ungraded in source; receipts are public and re-runnable: yale.edu, Yale Daily News, IRS 990s.)"
  },
  {
    "caveat": "do not claim production traders used it daily; it was demo-stage with production-grade plumbing",
    "edge": "below",
    "id": "L1",
    "sceneId": "trading-floor",
    "slot": "L1-framing",
    "text": "Built Agency MBS workflow products with institutional traders (co-founder was an ex-SquarePoint MBS quant); I know the blotter, BWIC, and TRACE workflows first-hand — and I ship at 14 PRs/week.",
    "grade": "UNGRADED",
    "gradeNote": "with"
  },
  {
    "chipLabel": "receipt: v1 repo (private; routers/utilities enumerable on request)",
    "edge": "below",
    "id": "L1",
    "sceneId": "trading-floor",
    "slot": "L1-receipts",
    "text": "11 domain routers (bwic, collateral_sourcing, prepay, sec_master_viewer…), a layered ELT data platform with ETF retrievers and SharePoint ingestion, SIFMA calendar/settlement utils, OAS/cheapness scoring, guarded prepay query building with server-rendered plots",
    "grade": "UNGRADED",
    "gradeNote": "with"
  },
  {
    "caveat": "Withdrawn at dissolution; receipts = Collin's screenshots and demo videos",
    "chipHref": "https://medlock.ai/",
    "chipLabel": "live: medlock.ai (MCP endpoint at /api/mcp)",
    "edge": "below",
    "id": "S3",
    "sceneId": "airport-gate",
    "slot": "S3",
    "text": "Production MCP server (medlock.ai) live July 2025, eight months after Anthropic shipped MCP and ~4 months after the Streamable HTTP transport entered the spec. Then the Visit Emery ChatGPT app approved by OpenAI and published to the app directory within ~5 months of the directory opening (Dec 17, 2025)",
    "grade": "BULLETPROOF",
    "gradeNote": "BULLETPROOF with the stated receipts."
  },
  {
    "chipLabel": "receipt: commit dates (git history)",
    "edge": "below",
    "id": "F4",
    "sceneId": "airport-gate",
    "slot": "F4",
    "text": "Pivot merged Mar 7, 2026 → first ChatGPT app merged in 27 days → first live destination tenant in 31 days → live booking-vendor integration (Ventrata/OCTO) in 48 days → app-store submission packet in 66 days. 132 PRs in 9.5 weeks (14/week; 10 merged on May 12 alone).",
    "grade": "BULLETPROOF",
    "gradeNote": "BULLETPROOF."
  },
  {
    "chipLabel": "receipt: commit dates (git history)",
    "edge": "below",
    "id": "S4",
    "sceneId": "colophon",
    "slot": "S4",
    "text": "I've been early three times in a row — enterprise LLMs in 2022, voice-LLM health in 2024, MCP apps in 2025 — and I have the commit dates to prove it.",
    "grade": "UNGRADED",
    "gradeNote": ""
  }
] as const;

export const FACTS_SOURCE_SHA256 = "e5ad4dd537c29d26f0b0f624f54a23535a69e7ba7add4dfbe2944e871ff96d22";
