/** Site-wide identity, navigation, and footer content. Copy lives here, never in components. */

export const SITE = {
  description: "Collin Bentley — a portfolio that teaches. The journey of a teacher who builds: equine therapy, Yale CS, robots, Beijing classrooms, health AI, and MCP-native products.",
  domain: "cdbentley.com",
  email: "collin.bentley@me.com",
  github: "https://github.com/collinbentley1",
  linkedin: "https://www.linkedin.com/in/collinbentley",
  name: "Collin Bentley",
  origin: "https://cdbentley.com",
  repo: "https://github.com/collinbentley1/cdbentley",
  tagline: "The journey of a teacher who builds",
  title: "Collin Bentley — The Journey",
} as const;

export const NAV = [
  { href: "/", label: "THE JOURNEY" },
  { href: "/work", label: "THE WORK" },
  { href: "/dojo", label: "THE DOJO" },
  { href: "/notes", label: "THE NOTES" },
] as const;

export const COLOPHON = {
  body: [
    "Cairns are the marker this site is built around: stacked stones travelers leave so the next person finds the path. That is what teaching is — and every chapter of this journey was a version of it.",
    "The site itself is a pure Bun app, front and back, on my own Bun/Cloud Run platform — SHA-pinned GitHub Actions, IaC scanned with Checkov, dependencies screened by Socket, Docker Hardened Images, and PR-preview environments that spin up and tear down with every pull request.",
    "Pixel art is generated by a small TypeScript pipeline in this repo — a hand-rolled PNG codec, hand-authored sprite grids, no game-engine assets.",
  ],
  repoLabel: "read the source",
  title: "COLOPHON",
} as const;
