name: Application

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  verify:
    name: Bun verify
    permissions:
      contents: read
    uses: collinbentley1/platform/.github/workflows/application.yml@8cefb91ab8d20c0bbfef7feab2d2b15d76785632
