name: Socket Firewall

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  firewall:
    name: Socket Firewall
    permissions:
      contents: read
    uses: collinbentley1/platform/.github/workflows/socket-firewall.yml@8cefb91ab8d20c0bbfef7feab2d2b15d76785632
